name: pylinkage-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.3.4=py38h06a4308_0
  - matplotlib-base=3.3.4=py38h62a2d02_0
  - numpy=1.20.2=py38h2d18471_0
  - numpy-base=1.20.2=py38hfae3a4d_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - pip:
    - pyswarms>=1.3.0
