name: pylinkage-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib>=3.3.4
  - matplotlib-base>=3.3.4
  - numpy>=1.20.2
  - numpy-base>=1.20.2
  - numpydoc>=1.1.0
  - pip
  - tqdm>=4.40.0
  - pip:
    - pyswarms>=1.3.0
